<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sourceTabName</name>
   <tag></tag>
   <elementGuidId>c7aa1472-e228-440f-9486-fc01fdee0a98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.p-verification__top-item-note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class=&quot;p-verification__top-item-note&quot;])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
