<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subjectTabName</name>
   <tag></tag>
   <elementGuidId>2afa1977-4194-48b3-9011-1cb48f9ef559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.p-verification__top-item-note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class=&quot;p-verification__top-item-note&quot;])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
