<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tableCell</name>
   <tag></tag>
   <elementGuidId>d85a13cc-be33-4604-9d16-c635151541a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//tbody[@class=&quot;ant-table-tbody&quot;])[2]/tr[${row_index}]/td[${column_index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
