<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pcpCenter</name>
   <tag></tag>
   <elementGuidId>2166590e-065f-453d-967b-8953b45bb662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='box__title']//ancestor::div[@class='box'])[4]//div[@class=&quot;values__value&quot;][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
