<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pcpDep</name>
   <tag></tag>
   <elementGuidId>99f41355-a5f6-48cc-b6d3-4b725b2576e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='box__title']//ancestor::div[@class='box'])[4]//div[@class=&quot;values__value&quot;][3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
